const express = require("express");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 5000;

// 500 real, widely-used domains
const realDomains = [
  // Tech giants & social (1-50)
  "https://www.google.com",
  "https://www.youtube.com",
  "https://www.facebook.com",
  "https://www.instagram.com",
  "https://www.twitter.com",
  "https://www.linkedin.com",
  "https://www.amazon.com",
  "https://www.netflix.com",
  "https://www.microsoft.com",
  "https://www.apple.com",
  "https://www.cloudflare.com",
  "https://www.wikipedia.org",
  "https://www.reddit.com",
  "https://www.yahoo.com",
  "https://www.bing.com",
  "https://www.github.com",
  "https://www.stackoverflow.com",
  "https://www.tiktok.com",
  "https://www.adobe.com",
  "https://www.paypal.com",
  "https://www.salesforce.com",
  "https://www.dropbox.com",
  "https://www.spotify.com",
  "https://www.wordpress.com",
  "https://www.medium.com",
  "https://www.quora.com",
  "https://www.pinterest.com",
  "https://www.zoom.us",
  "https://www.slack.com",
  "https://www.shopify.com",
  "https://www.ebay.com",
  "https://www.twitch.tv",
  "https://www.cnn.com",
  "https://www.bbc.com",
  "https://www.nytimes.com",
  "https://www.theguardian.com",
  "https://www.forbes.com",
  "https://www.imdb.com",
  "https://www.booking.com",
  "https://www.airbnb.com",
  "https://www.uber.com",
  "https://www.lyft.com",
  "https://www.discord.com",
  "https://www.roblox.com",
  "https://www.ibm.com",
  "https://www.intel.com",
  "https://www.oracle.com",
  "https://www.hp.com",
  "https://www.dell.com",
  "https://www.nvidia.com",
  // Tech & infrastructure (51-100)
  "https://www.tesla.com",
  "https://www.cisco.com",
  "https://www.mozilla.org",
  "https://www.okta.com",
  "https://www.stripe.com",
  "https://www.hubspot.com",
  "https://www.zendesk.com",
  "https://www.mailchimp.com",
  "https://www.canva.com",
  "https://www.figma.com",
  "https://www.atlassian.com",
  "https://www.digitalocean.com",
  "https://www.heroku.com",
  "https://www.vercel.com",
  "https://www.netlify.com",
  "https://www.fastly.com",
  "https://www.akamai.com",
  "https://www.target.com",
  "https://www.walmart.com",
  "https://www.bestbuy.com",
  "https://www.costco.com",
  "https://www.homedepot.com",
  "https://www.lowes.com",
  "https://www.mcdonalds.com",
  "https://www.starbucks.com",
  "https://www.nike.com",
  "https://www.adidas.com",
  "https://www.zara.com",
  "https://www.hm.com",
  "https://www.ikea.com",
  "https://www.etsy.com",
  "https://www.weibo.com",
  "https://www.baidu.com",
  "https://www.aliexpress.com",
  "https://www.alibaba.com",
  "https://www.samsung.com",
  "https://www.sony.com",
  "https://www.snapchat.com",
  "https://www.whatsapp.com",
  "https://www.telegram.org",
  "https://www.vimeo.com",
  "https://www.soundcloud.com",
  "https://www.coursera.org",
  "https://www.udemy.com",
  "https://www.khanacademy.org",
  "https://www.edx.org",
  "https://www.duolingo.com",
  "https://www.grammarly.com",
  "https://www.notion.so",
  "https://www.airtable.com",
  // News & media (101-150)
  "https://www.washingtonpost.com",
  "https://www.wsj.com",
  "https://www.reuters.com",
  "https://www.bloomberg.com",
  "https://www.cnbc.com",
  "https://www.foxnews.com",
  "https://www.nbcnews.com",
  "https://www.abcnews.go.com",
  "https://www.cbsnews.com",
  "https://www.usatoday.com",
  "https://www.huffpost.com",
  "https://www.buzzfeed.com",
  "https://www.vice.com",
  "https://www.vox.com",
  "https://www.theatlantic.com",
  "https://www.newyorker.com",
  "https://www.wired.com",
  "https://www.techcrunch.com",
  "https://www.theverge.com",
  "https://www.engadget.com",
  "https://www.mashable.com",
  "https://www.gizmodo.com",
  "https://www.cnet.com",
  "https://www.zdnet.com",
  "https://www.tomshardware.com",
  "https://www.anandtech.com",
  "https://www.arstechnica.com",
  "https://www.slashdot.org",
  "https://www.hackernews.com",
  "https://www.producthunt.com",
  "https://www.dribbble.com",
  "https://www.behance.net",
  "https://www.deviantart.com",
  "https://www.artstation.com",
  "https://www.500px.com",
  "https://www.flickr.com",
  "https://www.unsplash.com",
  "https://www.pexels.com",
  "https://www.shutterstock.com",
  "https://www.gettyimages.com",
  "https://www.istockphoto.com",
  "https://www.depositphotos.com",
  "https://www.dreamstime.com",
  "https://www.stocksy.com",
  "https://www.eyeem.com",
  "https://www.fotor.com",
  "https://www.pixlr.com",
  "https://www.photopea.com",
  "https://www.remove.bg",
  "https://www.tinypng.com",
  // E-commerce & retail (151-200)
  "https://www.wayfair.com",
  "https://www.overstock.com",
  "https://www.newegg.com",
  "https://www.bhphotovideo.com",
  "https://www.adorama.com",
  "https://www.macys.com",
  "https://www.nordstrom.com",
  "https://www.bloomingdales.com",
  "https://www.sephora.com",
  "https://www.ulta.com",
  "https://www.bathandbodyworks.com",
  "https://www.victoriassecret.com",
  "https://www.gap.com",
  "https://www.oldnavy.com",
  "https://www.bananarepublic.com",
  "https://www.jcrew.com",
  "https://www.uniqlo.com",
  "https://www.forever21.com",
  "https://www.asos.com",
  "https://www.boohoo.com",
  "https://www.shein.com",
  "https://www.fashionnova.com",
  "https://www.revolve.com",
  "https://www.freepeople.com",
  "https://www.urbanoutfitters.com",
  "https://www.anthropologie.com",
  "https://www.potterybarn.com",
  "https://www.crateandbarrel.com",
  "https://www.cb2.com",
  "https://www.westelm.com",
  "https://www.restorationhardware.com",
  "https://www.williams-sonoma.com",
  "https://www.surlatable.com",
  "https://www.bedbathandbeyond.com",
  "https://www.pier1.com",
  "https://www.worldmarket.com",
  "https://www.containerstore.com",
  "https://www.staples.com",
  "https://www.officedepot.com",
  "https://www.vistaprint.com",
  "https://www.moo.com",
  "https://www.zazzle.com",
  "https://www.redbubble.com",
  "https://www.teepublic.com",
  "https://www.threadless.com",
  "https://www.society6.com",
  "https://www.cafepress.com",
  "https://www.spreadshirt.com",
  "https://www.printful.com",
  "https://www.gooten.com",
  // Finance & business (201-250)
  "https://www.chase.com",
  "https://www.bankofamerica.com",
  "https://www.wellsfargo.com",
  "https://www.citi.com",
  "https://www.capitalone.com",
  "https://www.americanexpress.com",
  "https://www.discover.com",
  "https://www.usbank.com",
  "https://www.pnc.com",
  "https://www.tdbank.com",
  "https://www.schwab.com",
  "https://www.fidelity.com",
  "https://www.vanguard.com",
  "https://www.etrade.com",
  "https://www.robinhood.com",
  "https://www.coinbase.com",
  "https://www.kraken.com",
  "https://www.binance.com",
  "https://www.gemini.com",
  "https://www.blockchain.com",
  "https://www.wise.com",
  "https://www.remitly.com",
  "https://www.xoom.com",
  "https://www.westernunion.com",
  "https://www.moneygram.com",
  "https://www.venmo.com",
  "https://www.cash.app",
  "https://www.zelle.com",
  "https://www.affirm.com",
  "https://www.klarna.com",
  "https://www.afterpay.com",
  "https://www.sezzle.com",
  "https://www.quadpay.com",
  "https://www.bread.com",
  "https://www.splitit.com",
  "https://www.credova.com",
  "https://www.upstart.com",
  "https://www.sofi.com",
  "https://www.lendingclub.com",
  "https://www.prosper.com",
  "https://www.marcus.com",
  "https://www.ally.com",
  "https://www.synchrony.com",
  "https://www.greendot.com",
  "https://www.chime.com",
  "https://www.current.com",
  "https://www.varo.com",
  "https://www.monzo.com",
  "https://www.revolut.com",
  "https://www.n26.com",
  // Travel & hospitality (251-300)
  "https://www.expedia.com",
  "https://www.hotels.com",
  "https://www.priceline.com",
  "https://www.kayak.com",
  "https://www.trivago.com",
  "https://www.tripadvisor.com",
  "https://www.yelp.com",
  "https://www.opentable.com",
  "https://www.resy.com",
  "https://www.doordash.com",
  "https://www.ubereats.com",
  "https://www.grubhub.com",
  "https://www.postmates.com",
  "https://www.instacart.com",
  "https://www.shipt.com",
  "https://www.gopuff.com",
  "https://www.drizly.com",
  "https://www.minibar.com",
  "https://www.vivino.com",
  "https://www.wine.com",
  "https://www.totalwine.com",
  "https://www.bevmo.com",
  "https://www.freshdirect.com",
  "https://www.peapod.com",
  "https://www.safeway.com",
  "https://www.kroger.com",
  "https://www.publix.com",
  "https://www.albertsons.com",
  "https://www.wegmans.com",
  "https://www.wholefoodsmarket.com",
  "https://www.traderjoes.com",
  "https://www.sprouts.com",
  "https://www.aldi.com",
  "https://www.lidl.com",
  "https://www.tesco.com",
  "https://www.sainsburys.co.uk",
  "https://www.asda.com",
  "https://www.morrisons.com",
  "https://www.waitrose.com",
  "https://www.ocado.com",
  "https://www.marksandspencer.com",
  "https://www.johnlewis.com",
  "https://www.argos.co.uk",
  "https://www.currys.co.uk",
  "https://www.ao.com",
  "https://www.very.co.uk",
  "https://www.next.co.uk",
  "https://www.boohoo.com",
  "https://www.prettylittlething.com",
  "https://www.missguided.com",
  // Gaming & entertainment (301-350)
  "https://www.steam.com",
  "https://www.epicgames.com",
  "https://www.ea.com",
  "https://www.ubisoft.com",
  "https://www.activision.com",
  "https://www.blizzard.com",
  "https://www.riotgames.com",
  "https://www.valvesoftware.com",
  "https://www.bethesda.net",
  "https://www.rockstargames.com",
  "https://www.2k.com",
  "https://www.nintendo.com",
  "https://www.playstation.com",
  "https://www.xbox.com",
  "https://www.gog.com",
  "https://www.humblebundle.com",
  "https://www.greenmangaming.com",
  "https://www.fanatical.com",
  "https://www.cdkeys.com",
  "https://www.g2a.com",
  "https://www.kinguin.net",
  "https://www.gamestop.com",
  "https://www.gamespot.com",
  "https://www.ign.com",
  "https://www.kotaku.com",
  "https://www.polygon.com",
  "https://www.pcgamer.com",
  "https://www.rockpapershotgun.com",
  "https://www.eurogamer.net",
  "https://www.destructoid.com",
  "https://www.giantbomb.com",
  "https://www.escapistmagazine.com",
  "https://www.vg247.com",
  "https://www.dualshockers.com",
  "https://www.pushsquare.com",
  "https://www.nintendolife.com",
  "https://www.purexbox.com",
  "https://www.timeextension.com",
  "https://www.siliconera.com",
  "https://www.rpgsite.net",
  "https://www.mmorpg.com",
  "https://www.wowhead.com",
  "https://www.icy-veins.com",
  "https://www.mobafire.com",
  "https://www.op.gg",
  "https://www.u.gg",
  "https://www.blitz.gg",
  "https://www.tracker.gg",
  "https://www.faceit.com",
  "https://www.esea.net",
  // Developer tools (351-400)
  "https://www.gitlab.com",
  "https://www.bitbucket.org",
  "https://www.sourceforge.net",
  "https://www.codepen.io",
  "https://www.jsfiddle.net",
  "https://www.codesandbox.io",
  "https://www.replit.com",
  "https://www.glitch.com",
  "https://www.stackblitz.com",
  "https://www.codeanywhere.com",
  "https://www.gitpod.io",
  "https://www.coder.com",
  "https://www.jetbrains.com",
  "https://www.visualstudio.com",
  "https://www.sublimetext.com",
  "https://www.atom.io",
  "https://www.brackets.io",
  "https://www.notepad-plus-plus.org",
  "https://www.vim.org",
  "https://www.gnu.org",
  "https://www.docker.com",
  "https://www.kubernetes.io",
  "https://www.terraform.io",
  "https://www.ansible.com",
  "https://www.puppet.com",
  "https://www.chef.io",
  "https://www.saltstack.com",
  "https://www.jenkins.io",
  "https://www.circleci.com",
  "https://www.travis-ci.com",
  "https://www.semaphoreci.com",
  "https://www.buildkite.com",
  "https://www.drone.io",
  "https://www.teamcity.com",
  "https://www.bamboo.com",
  "https://www.codeship.com",
  "https://www.buddy.works",
  "https://www.codefresh.io",
  "https://www.harness.io",
  "https://www.spinnaker.io",
  "https://www.argocd.io",
  "https://www.fluxcd.io",
  "https://www.pulumi.com",
  "https://www.crossplane.io",
  "https://www.datadoghq.com",
  "https://www.newrelic.com",
  "https://www.splunk.com",
  "https://www.elastic.co",
  "https://www.grafana.com",
  "https://www.prometheus.io",
  // Cloud & SaaS (401-450)
  "https://www.aws.amazon.com",
  "https://www.cloud.google.com",
  "https://www.azure.microsoft.com",
  "https://www.linode.com",
  "https://www.vultr.com",
  "https://www.render.com",
  "https://www.railway.app",
  "https://www.fly.io",
  "https://www.deno.com",
  "https://www.supabase.com",
  "https://www.firebase.google.com",
  "https://www.planetscale.com",
  "https://www.neon.tech",
  "https://www.cockroachlabs.com",
  "https://www.timescale.com",
  "https://www.influxdata.com",
  "https://www.mongodb.com",
  "https://www.redis.com",
  "https://www.memcached.org",
  "https://www.couchbase.com",
  "https://www.datastax.com",
  "https://www.neo4j.com",
  "https://www.arangodb.com",
  "https://www.fauna.com",
  "https://www.hasura.io",
  "https://www.prisma.io",
  "https://www.sequelize.org",
  "https://www.typeorm.io",
  "https://www.objection.js",
  "https://www.knexjs.org",
  "https://www.bookshelfjs.org",
  "https://www.mikro-orm.io",
  "https://www.drizzle.team",
  "https://www.kysely.dev",
  "https://www.slonik.dev",
  "https://www.pgbouncer.org",
  "https://www.pgpool.net",
  "https://www.citusdata.com",
  "https://www.yugabyte.com",
  "https://www.vitess.io",
  "https://www.tidb.io",
  "https://www.oceanbase.com",
  "https://www.singlestore.com",
  "https://www.clickhouse.com",
  "https://www.duckdb.org",
  "https://www.snowflake.com",
  "https://www.databricks.com",
  "https://www.fivetran.com",
  "https://www.airbyte.com",
  "https://www.stitch.com",
  // Health, sports & lifestyle (451-500)
  "https://www.webmd.com",
  "https://www.mayoclinic.org",
  "https://www.healthline.com",
  "https://www.medicalnewstoday.com",
  "https://www.everydayhealth.com",
  "https://www.drugs.com",
  "https://www.goodrx.com",
  "https://www.zocdoc.com",
  "https://www.teladoc.com",
  "https://www.onemedical.com",
  "https://www.peloton.com",
  "https://www.mirror.co",
  "https://www.tonal.com",
  "https://www.hydrow.com",
  "https://www.nordictrack.com",
  "https://www.bowflex.com",
  "https://www.lululemon.com",
  "https://www.gymshark.com",
  "https://www.underarmour.com",
  "https://www.puma.com",
  "https://www.reebok.com",
  "https://www.newbalance.com",
  "https://www.asics.com",
  "https://www.brooks.com",
  "https://www.hoka.com",
  "https://www.on-running.com",
  "https://www.allbirds.com",
  "https://www.rothys.com",
  "https://www.everlane.com",
  "https://www.patagonia.com",
  "https://www.rei.com",
  "https://www.backcountry.com",
  "https://www.moosejaw.com",
  "https://www.evo.com",
  "https://www.steepandcheap.com",
  "https://www.campsaver.com",
  "https://www.trailspace.com",
  "https://www.gearjunkie.com",
  "https://www.outsideonline.com",
  "https://www.backpacker.com",
  "https://www.trailrunnermag.com",
  "https://www.runnersworld.com",
  "https://www.bicycling.com",
  "https://www.cyclingnews.com",
  "https://www.bikeradar.com",
  "https://www.pinkbike.com",
  "https://www.mtbr.com",
  "https://www.singletracks.com",
  "https://www.trailforks.com",
  "https://www.strava.com"
];


// Serve hero image same-origin
app.use(express.static(__dirname));

app.get("/test", (req, res) => {
  const count = parseInt(req.query.preconnectCount || "0", 10);
  const selected = realDomains.slice(0, Math.min(count, realDomains.length));


  let preconnects = "";
  for (const domain of selected) {
    preconnects += `<link rel="preconnect" href="${domain}" crossorigin>\n`;
  }

  const html = `
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Preconnect Test (${count})</title>

      ${preconnects}

      <style>
        body { margin: 0; font-family: system-ui, -apple-system, sans-serif; }
        nav { background: #111; color: white; padding: 16px 32px; display: flex; justify-content: space-between; }
        nav a { color: white; text-decoration: none; margin-left: 16px; }
        .hero { width: 100%; height: 80vh; object-fit: cover; display: block; }
        .content { max-width: 800px; margin: 40px auto; padding: 0 20px; }
        .card { background: #f5f5f5; padding: 20px; margin: 20px 0; border-radius: 8px; }
      </style>
    </head>
    <body>

      <nav>
        <div>Preconnect Test</div>
        <div>
          <a href="/test">0</a>
          <a href="/test?preconnectCount=100">100</a>
          <a href="/test?preconnectCount=300">300</a>
          <a href="/test?preconnectCount=500">500</a>
        </div>
      </nav>

      <img
        src="smallhero.jpg"
        width="1600"
        height="900"
        alt="Hero"
        class="hero"
        fetchpriority="high" 
      />

      <div class="content">
        <h1>Preconnect Count: ${count}</h1>
        <p>
          This page dynamically injects ${count} preconnect hints
          while the LCP image loads from the same origin.
        </p>

        <div class="card">
          <h2>Test Section</h2>
          <p>Used to simulate normal page content.</p>
        </div>

        <div class="card">
          <h2>Another Section</h2>
          <p>More layout content.</p>
        </div>
      </div>


    </body>
  </html>
  `;

  res.setHeader("Content-Type", "text/html");
  res.send(html);
});

app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
